[package]
edition = "2021"
name = "rust-project-template"
version = "0.1.0"

[dependencies]
crossterm = "0.29.*"

[profile.release]
codegen-units = 1
debug = false
lto = "fat"
opt-level = 3

[profile.dev]
incremental = true

[build]
rustc-wrapper = "sccache"
